server:
  port: 5000

spring:
  datasource:
    url: jdbc:postgresql://localhost:8002/ate_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    schema: classpath:/static/schema.sql
    initialization-mode: always
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext